version: "3.8"
services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
      - config-server
      - address-service
      - business-service
      - order-service
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server

  business-service:
    build: ./business-service
    container_name: business-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server

  address-service:
    build: ./address-service
    container_name: address-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server
