server:
  port: 8082

spring:
  application:
    name: BUSINESS-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/elm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ynu.edu.businessservice.po
  global-config:
    db-config:
      id-type: auto

# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    ynu.edu.businessservice: debug 