server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: business-service
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/api/business/**,/api/food/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/cart/**,/api/order/**,/api/orders/**
          filters:
            - StripPrefix=1
        - id: address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/api/address/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always