server:
  port: 8083

spring:
  application:
    name: ADDRESS-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/elm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ynu.edu.addressservice.po
  global-config:
    db-config:
      id-type: auto

# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    ynu.edu.addressservice: debug 