server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/elm?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ynu.edu.orderservice.po
  global-config:
    db-config:
      id-type: auto

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 日志配置
logging:
  level:
    ynu.edu.orderservice: debug
    ynu.edu.orderservice.feign: debug 